# Generated by Django 5.0.1 on 2024-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', null=True, upload_to='contact_image/')),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=1000)),
                ('heading', models.CharField(default='An article', max_length=1000)),
                ('estimated_time', models.IntegerField(default=0, null=True)),
                ('article', models.TextField(default='', max_length=1000000)),
                ('image', models.ImageField(default='', upload_to='')),
                ('branch', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0, null=True)),
                ('slug', models.CharField(max_length=130)),
                ('unique_identifier', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=1000)),
                ('heading', models.CharField(default='An article', max_length=1000)),
                ('estimated_time', models.IntegerField(default=0, null=True)),
                ('article', models.TextField(default='', max_length=1000000)),
                ('image', models.ImageField(default='', null=True, upload_to='')),
                ('insta', models.CharField(default='', max_length=1000)),
                ('reg_no', models.BigIntegerField(default=0, null=True)),
                ('branch', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0, null=True)),
                ('phone_no', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
