# Generated by Django 5.0.1 on 2024-06-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='phone_no',
        ),
    ]
