# Generated by Django 4.1.5 on 2023-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='art',
            field=models.CharField(default='', max_length=10000000000000000000000000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='article',
            field=models.TextField(default='', max_length=10000000000000000000000),
        ),
    ]
