# Generated by Django 5.0.1 on 2024-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email_id', models.CharField(default='', max_length=1000)),
                ('heading', models.CharField(default='An article', max_length=100)),
                ('estimated_time', models.IntegerField(default=0, null=True)),
                ('article', models.CharField(default='', max_length=1000000000000000000)),
                ('image', models.ImageField(default='', upload_to='')),
                ('branch', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0, null=True)),
                ('slug', models.CharField(max_length=130)),
                ('unique_identifier', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
