# Generated by Django 4.1.5 on 2023-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0002_post_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
