# Generated by Django 4.1.5 on 2023-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='art',
            field=models.CharField(default='', max_length=1000000000000000000000000),
        ),
    ]
